import os
import random
import json
import datetime
import psycopg2
from dotenv import load_dotenv

# Carrega as credenciais do banco de dados do arquivo .env
load_dotenv()

DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME", "postgres")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")

conn_params = {
    "host": DB_HOST,
    "port": DB_PORT,
    "database": DB_NAME,
    "user": DB_USER,
    "password": DB_PASSWORD
}

# Listas de dados para geracao realista
nomes = ["Ana Silva", "Beatriz Santos", "Carlos Souza", "Daniel Oliveira", "Eduarda Lima", 
         "Felipe Costa", "Gabriela Pereira", "Heitor Rodrigues", "Isabela Almeida", "João Carvalho",
         "Larissa Ferreira", "Marcos Gomes", "Natália Martins", "Otávio Rocha", "Patrícia Ribeiro",
         "Rafael Alves", "Sofia Mendes", "Thiago Silva", "Vanessa Barbosa", "Lucas Pinto"]

emails_dominios = ["gmail.com", "yahoo.com.br", "hotmail.com", "outlook.com"]

mensagens_humanas = [
    "Olá, gostaria de agendar uma consulta.",
    "Vocês têm horário disponível para amanhã à tarde?",
    "Quais são as especialidades atendidas na clínica?",
    "Preciso remarcar meu procedimento de botox.",
    "Qual o valor da sessão de limpeza de pele?",
    "Gostaria de cancelar meu agendamento de quinta-feira.",
    "Preciso falar com a administração sobre um documento.",
    "Como funciona a primeira consulta de avaliação?",
    "Vocês aceitam plano de saúde para procedimentos?"
]

respostas_ia = [
    "Olá! Como posso te ajudar hoje?",
    "Tenho horários disponíveis amanhã às 14:00 e às 16:30. Qual prefere?",
    "Atendemos dermatologia, estética avançada e fisioterapia dermatofuncional.",
    "Claro, podemos remarcar. Qual o melhor dia para você na próxima semana?",
    "A sessão de limpeza de pele profunda está com valor sob consulta. Deseja agendar uma avaliação?",
    "Agendamento cancelado com sucesso. Se precisar de um novo horário, só avisar.",
    "Entendido. Vou direcionar sua solicitação para a equipe administrativa.",
    "A primeira consulta de avaliação serve para mapear suas necessidades e traçar um plano de tratamento personalizado.",
    "Trabalhamos com reembolso de planos de saúde e emitimos toda a documentação necessária."
]

def criar_tabelas_se_nao_existirem(cursor):
    """Cria a estrutura das tabelas da Minerva no banco financeiro para simular integracao"""
    print("Verificando/Criando estrutura de tabelas da Minerva...")
    
    leads_table_query = """
    CREATE TABLE IF NOT EXISTS public.cyrius_leads_minerva_telegram (
        telegram_id text null,
        nome text null,
        email text null,
        criado_em timestamp without time zone null default now(),
        session_id bigint not null,
        constraint cyrius_leads_minerva_telegram_pkey primary key (session_id)
    );
    """
    
    agente_table_query = """
    CREATE TABLE IF NOT EXISTS public.cyrius_agente_minerva_telegram (
        id integer generated by default as identity not null,
        session_id bigint not null,
        created_at timestamp with time zone not null default now(),
        telegram_id text null,
        nome text null,
        email text null,
        empresa text null,
        setor text null,
        cargo text null,
        message jsonb null,
        messages jsonb null,
        processed boolean not null default false,
        processing boolean not null default false,
        batch_id text null,
        constraint cyrius_agente_minerva_telegram_pkey primary key (id),
        constraint cyrius_agente_minerva_telegram_session_id_fkey foreign KEY (session_id) references cyrius_leads_minerva_telegram (session_id)
    );
    """
    cursor.execute(leads_table_query)
    cursor.execute(agente_table_query)

def gerar_dados():
    conn = psycopg2.connect(**conn_params)
    cursor = conn.cursor()
    
    # 1. Garante que as tabelas existam no banco financeiro
    criar_tabelas_se_nao_existirem(cursor)
    conn.commit()
    
    print("Iniciando geração de dados fictícios para o portfólio...")
    
    # 2. Limpa dados de teste anteriores de forma segura
    cursor.execute("DELETE FROM public.cyrius_agente_minerva_telegram WHERE session_id >= 5511900000000;")
    cursor.execute("DELETE FROM public.cyrius_leads_minerva_telegram WHERE session_id >= 5511900000000;")
    
    total_leads = 100
    for i in range(total_leads):
        nome = random.choice(nomes)
        primeiro_nome = nome.split()[0].lower()
        sobrenome = nome.split()[1].lower()
        email = f"{primeiro_nome}.{sobrenome}@{random.choice(emails_dominios)}"
        
        session_id = 5511900000000 + i
        telegram_id = f"t_{session_id}"
        
        dias_atras = random.randint(0, 30)
        data_cadastro = datetime.datetime.now() - datetime.timedelta(days=dias_atras)
        
        cursor.execute("""
            INSERT INTO public.cyrius_leads_minerva_telegram (session_id, nome, email, criado_em, telegram_id)
            VALUES (%s, %s, %s, %s, %s);
        """, (session_id, nome, email, data_cadastro, telegram_id))
        
        qtd_mensagens = random.randint(2, 5)
        for j in range(qtd_mensagens):
            tipo = "human" if j % 2 == 0 else "ai"
            conteudo = random.choice(mensagens_humanas) if tipo == "human" else random.choice(respostas_ia)
            
            mensagem_json = {
                "type": tipo,
                "data": {
                    "content": conteudo,
                    "additional_kwargs": {}
                }
            }
            
            data_mensagem = data_cadastro + datetime.timedelta(minutes=j * 5)
            
            cursor.execute("""
                INSERT INTO public.cyrius_agente_minerva_telegram (session_id, message, created_at, telegram_id, nome, email)
                VALUES (%s, %s, %s, %s, %s, %s);
            """, (session_id, json.dumps(mensagem_json), data_mensagem, telegram_id, nome, email))
            
    conn.commit()
    cursor.close()
    conn.close()
    print(f"Sucesso! Tabelas criadas e gerados {total_leads} leads e mensagens de histórico correspondentes no Supabase.")

if __name__ == "__main__":
    gerar_dados()